package poly;

public enum Se { // StatusEnum
    START, END,
    ITEM_START, ITEM_END,
    FACTOR_START, FACTOR_EXP, FACTOR_SIGN, FACTOR_NUM, FACTOR_END,
    ESTART /*ELEMENT_START*/, ES /*ELEMENT_SIGN*/, EN /*ELEMENT_NUM*/,
        EV /*ELEMENT_VAR*/, ET /*ELEMENT_TRI*/, EE /*ELEMENT_END*/
}
