package poly;

public enum StatusEnum {
    START, END,
    ITEM_START, ITEM_END,
    FACTOR_START, FACTOR_EXP, FACTOR_SIGN, FACTOR_NUM, FACTOR_END,
    ELEMENT_START, ELEMENT_SIGN, ELEMENT_SIGN_ELEMENT, ELEMENT_SIGN_SPACE,
        ELEMENT_NUM, ELEMENT_VAR, ELEMENT_TRI, ELEMENT_END
}
